apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    run: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: my-app
        image: simonotter/simple-node:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
